### ISSUE TITLE
[BUG] permission error

### ISSUE THREAD

**Issue by robertalexandru12** [Silthus/sLimits#19] opened 2021-04-18 10:12 UTC
[13:07:57 ERROR]: [slimits] [ACF] Exception in command: slimits
[13:07:57 ERROR]: [slimits] [ACF] net.silthus.slimits.slib.configlib.ConfigurationException: The value of field 'permission' is null.
[13:07:57 ERROR]: [slimits] [ACF] Please assign a non-null default value or remove this field.
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.Validator.checkNotNull(Validator.java:17)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.FieldMapper.checkDefaultValueNull(FieldMapper.java:79)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.FieldMapper.toConvertibleObject(FieldMapper.java:33)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.FieldMapper.instanceToMap(FieldMapper.java:22)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.Converters$ConfigurationElementConverter.convertTo(Converters.java:527)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.Converters.tryConvertTo(Converters.java:49)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.Converters.convertTo(Converters.java:42)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.FieldMapper.toConvertibleObject(FieldMapper.java:36)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.FieldMapper.instanceToMap(FieldMapper.java:22)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.Configuration.save(Configuration.java:51)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.slib.configlib.configs.yaml.YamlConfiguration.loadAndSave(YamlConfiguration.java:49)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.storage.FlatFileLimitsStorage.createPlayerConfig(FlatFileLimitsStorage.java:68)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.storage.FlatFileLimitsStorage.load(FlatFileLimitsStorage.java:55)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.LimitsManager.loadPlayerLimit(LimitsManager.java:146)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.LimitsManager.getPlayerLimit(LimitsManager.java:104)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.commands.LimitsCommand.listLimits(LimitsCommand.java:38)
[13:07:57 ERROR]: [slimits] [ACF]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:07:57 ERROR]: [slimits] [ACF]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:07:57 ERROR]: [slimits] [ACF]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:07:57 ERROR]: [slimits] [ACF]       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.acf.BaseCommand.execute(BaseCommand.java:513)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.acf.RootCommand.execute(RootCommand.java:99)
[13:07:57 ERROR]: [slimits] [ACF]       at net.silthus.slimits.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[13:07:57 ERROR]: [slimits] [ACF]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:07:57 ERROR]: [slimits] [ACF]       at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2238)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2053)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2006)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1441)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
[13:07:57 ERROR]: [slimits] [ACF]       at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[13:07:57 ERROR]: [slimits] [ACF]       at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Silthus** [comment] 2021-05-31 05:02
Hi @robertalexandru12 
sorry for the late answer, I oversaw the issue.
Can you please post your config? This seems like a configuration issue where the `permission` field is not set.

**Comment by Silthus** [comment] 2021-05-31 05:47
This is a duplicate of #23

**Closed by Silthus** 2021-05-31 05:47 UTC
Labels: question
